num1 = int (input('Digite um número: '))
num2 = int(input('Digite outro número: '))
soma = int(num1 + num2)
#print('A soma ente ', num1, 'e ', num2, 'é: ', soma)
print('A soma entre {} e {} é {}'.format(num1, num2, soma))